### ISSUE TITLE
*.md links are not correctly reformatted relative to the rootDocsFolder

### ISSUE THREAD

**Issue by Lissy93** [cmbrose/github-docs-to-wiki#2]
Hi @cmbrose - this looks like a really useful action, awesome work! :)

I am facing a slight issue though, in that the links within my readme files don't seem to be correctly reformatted.

- My repo's documentation is located at `./docs`. I have set, `rootDocsFolder: ./docs` within my action.
- Within a file, I have for example a link to: `./docs/management.md`
- Expected outcome: Link would become `https://github.com/Lissy93/dashy/wiki/management`
- Actual outcome: Link becomes: `https://github.com/Lissy93/dashy/wiki/docs/management.md`

The docs say
> If a link is to another .md file within the docs path, convert the link to point to a wiki page

Am I doing something wrong? It seems like either I am specifying my links incorrectly, or doing something else wrong, or maybe it could be a bug. For reference, [here is my workflow file](https://github.com/Lissy93/dashy/blob/master/.github/workflows/wiki-sync.yml), and [this is my repo](https://github.com/Lissy93/dashy)

Thank you very much in advance :)

**Comment by cmbrose** [comment]
Hi @Lissy93! Apologies for the slow reply, I’ve been spending some time away from code with a new baby 😄  

I checked your repo and it looks like you’ve migrated on to a different wiki tool, but if you’re still interested in getting this to work I’m happy to dig into it!

**Comment by Lissy93** [comment]
Thanks for the reply, and congratulations on the baby! 

Yeah in the end I switched to an alternative, I'm still quite new to GH actions so was struggling to debug this one (but it very well could have been a problem on my part) so I'll close the issue, but thank you for your reply :)
